### ISSUE TITLE
Facing datasets error 

### ISSUE THREAD

**Issue by amit0623** [obss/jury#66] opened 2021-12-03 15:15 UTC
Hello,
After dowloading the contents from git and instantiating the object, i get this error :-

```python
/content/image-captioning-bottom-up-top-down
Traceback (most recent call last):
  File "eval.py", line 11, in <module>
   from jury import Jury 
  File "/usr/local/lib/python3.7/dist-packages/jury/__init__.py", line 1, in <module>
    from jury.core import Jury
  File "/usr/local/lib/python3.7/dist-packages/jury/core.py", line 6, in <module>
    from jury.metrics import EvaluationInstance, Metric, load_metric
  File "/usr/local/lib/python3.7/dist-packages/jury/metrics/__init__.py", line 1, in <module>
    from jury.metrics._core import (
  File "/usr/local/lib/python3.7/dist-packages/jury/metrics/_core/__init__.py", line 1, in <module>
    from jury.metrics._core.auto import AutoMetric, load_metric
  File "/usr/local/lib/python3.7/dist-packages/jury/metrics/_core/auto.py", line 23, in <module>
    from jury.metrics._core.base import Metric
  File "/usr/local/lib/python3.7/dist-packages/jury/metrics/_core/base.py", line 28, in <module>
    from datasets.utils.logging import get_logger
ModuleNotFoundError: No module named 'datasets.utils'; 'datasets' is not a package
```

Can you please check what could be the issue

**Comment by devrimcavusoglu** [comment] 2021-12-03 15:28
Hello @amit0623, can you please share a minimal code snippet to reproduce the behavior ? Also can you please specify what version you use for `datasets` and `jury` ?

**Comment by amit0623** [comment] 2021-12-03 15:37
Below are the steps 
Installation :- 
```
!git clone https://github.com/obss/jury.git
%cd jury
!python setup.py install
```

# Python Code 

`from jury import Jury ` > This fails 

after this is object creation

`jury_obj = Jury()`

Then intended  use would be 

`metrics_dict = jury_obj(predictions=references, references=hypotheses)
`
But I didnt reach this step.

Also, all installation is present on below path in colab

`/usr/local/lib/python3.7/dist-packag/usr/local/lib/
`
I even tried export, but it didnt work 
```

! echo $PYTHONPATH
%env PYTHONPATH="$/env/python:/usr/local/lib/python3.7/dist-packages/jury/"
! echo $PYTHONPATH
```

**Comment by devrimcavusoglu** [comment] 2021-12-03 15:51
I tried the exact same steps on Colab, and got it working. The issue might be that you need to restart your notebook after installing a package (this is mostly the case for any installation to refresh the environment) or another problem could be corrupted installation of dependent packages in such case you can try `pip install jury --ignore-installed --no-cache-dir`. My suggestions would be 

1. restart your kernel after installation, (Runtime > Restart Runtime)
2. try installing with pip instead of clone (use `pip install jury`, if you want to use the latest source code available on master try `pip install git+https://github.com/obss/jury.git`)

**Comment by amit0623** [comment] 2021-12-03 15:56
Just to check. - were you able to reproduce the issue as well.

**Comment by devrimcavusoglu** [comment] 2021-12-03 16:00
> Just to check. - were you able to reproduce the issue as well.

Nope, as I said I got it working, I couldn't reproduce your error. Again, it seems a corrupted installation of datasets package I guess. Can you confirm that any of the sugesstions worked for you ?

**Comment by amit0623** [comment] 2021-12-03 16:03
Let me give it a  try. Will respond back ASAP.

**Comment by devrimcavusoglu** [comment] 2021-12-03 21:06
Still, no idea, maybe there is a name clash for name `datasets`. However, this [SO post](https://stackoverflow.com/questions/68196815/modulenotfounderror-huggingface-datasets-in-jupyter-notebook) can help you I think. Also, check if you can run the Jury's example Colab notebook and if you can run that notebook without any error means that the problem is spesific to your Colab environment. Thus, I'll be closing the issue as the problem is not related to the package. Saying that, I think it is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/google-colaboratory) if the question I mentioned doesn't solve your problem.

**Closed by devrimcavusoglu** 2021-12-03 21:06 UTC
